config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
 get '/cart/:id' => 'cart#add'

  resources :products
  root 'page#home'
get 'page/home'

  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         #:registerable,
end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

 before_action :authenticate_user!, except: [:index]
 def add
  id= params[:id]
   if session[:cart] then
      cart = session[:cart]
   else
      session[:cart] = {}
      cart = session[:cart]
   end
   if cart[id] then
      cart[id] = cart[id] + 1
   else
      cart[id] = 1
   end
  redirect_to :action => :index
 end
def clearCart
   session[:cart] = nil
   redirect_to :action => :index
end
  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :image, :subcategory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Twój koszyk</h1>

<br>
<% if @cart.empty? %>
  <p>Your cart in currently empty</p>
<% else %>
  <%= link_to 'Wyczyść koszyk' , cart_clear_path %>
<% end %>

 <br>
  
 <br>
 <br>
 <br>
 <br>
 <% total = 0 %>

<ul>
   <% @cart.each do | id, quantity | %>
   <% product = Product.find_by_id(id) %>

    <li>
      <%= link_to product.title, product %>
      <br>
      <p><%= number_to_currency(product.price, :unit => 'PLN ') %><p>
      <p>Quantity: <%= quantity %></p>
     
    </li>
    <% total += quantity * product.price %>
    <p><%= number_to_currency(total, :unit => 'PLN ') %><p>
<br>
    

<% end %>
<p>Do zapłaty: <%= total %> PLN <p>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     
   
 <navi id="navi">
   <div id="page_navi">
<%= image_tag("myszunia.png", width: '61px') %>
     <font color="navy" size="5" face="Arial"> Sklep "Myszka"</font>
     
     <br>
     <%= link_to "Home", new_user_session_path %>
     <%= link_to "Produkty", products_path %> 
     <%= link_to "O sklepie", page_about_path %>
     <%= link_to "Dostawa", page_faqs_path %>
     <%= link_to "Kontakt", page_contact_path %>

   </div>
 <div id="sign_in">
<% if user_signed_in? %>
        <%= link_to "Wyloguj", destroy_user_session_path, method: :delete %>
     <% else %>
	<%= link_to "Zaloguj", new_user_session_path  %>


	<%= link_to "Zarejestruj", new_user_registration_path  %> 
     <% end %>
 </div>
  </navi>

<div id="main_wrap">
 	<p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>

<div class="container-fluid">
   <div class="row">
    <div class="col-md-12">
    <%= yield %>
    </div>
    </div>
   </div>
</div>

</body>
</html>

app/views/page/about.html.erb
<h1>Sklep został utworzony przez <font color="navy" underline="true">rafal.on@o2.pl</font></h1>
<br>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Kontak do autora: <font color="navy" underline="tre">rafal.on@o2.pl</font></h1>

<br>

app/views/page/faqs.html.erb
<h1>Dostawa</h1>
<br>
<p>Sposoby dostawy</p>

app/views/page/home.html.erb
<h1>To jest sklep   </h1>
<br>
<p>Find me in app/views/page/home.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.cktext_area  :description %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edycja Produktu:</h1>
<br>
<%= render 'form' %>
<% if admin_signed_in? %>
    
     <%= link_to "Kasuj", @product, method: :delete, data: { confirm: 'Czy jesteś pewien?' } %>
     <% end %>

 
<%= link_to 'Show', @product %>
<%= link_to 'Back', products_path %> 

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><font color="green">Lista  produktów:</font></h1>
<br>

<table align="center">
  <thead>
    <tr>
      <th>     </th>
     
      <th>Nazwa</th>
      <th>Cena PLN</th>
        
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <td ><%= image_tag(product.image_url, width: '61px') %></td
        <td><%=  %></td>
         
        <td><%= product.title %></td> 
        <td><%= product.price %></td>
        
         
        
        <td><%= link_to 'Pokaż', product %></td>
       
        
       <td> <a href = "/cart/<%= product.id %>">Dodaj do koszyka </a></td>        

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
  <a href="/products/new"><button > Nowy produkt</button></a>
<% end %>

 <a href="/products/new"><button > Nowy produkt</button></a>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Specyfikacja produktu:<h1>
<p>
 <br>
  <strong>Nazwa produktu:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Opis:</strong>
  <%= raw @product.description %>
</p>

<p>
  <strong>Cena PLN:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Kategoria:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Podkategoria:</strong>
  <%= @product.subcategory %>
</p>

<p>
  <strong>Obrazek:</strong>
  <%= @product.image  %>
<br>
 <%= image_tag(@product.image_url, width: '61px') %>
</p>
<font size="3"><%= link_to 'Edycja produktu  ', edit_product_path(@product) %></font> 
<font size="3">  | <font>
<font size="3"><%= link_to 'Cofnij', products_path %></font>